name: GCP OIDC Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # REQUIRED
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/707328741715/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-sa@infra-triumph-360214.iam.gserviceaccount.com

      - name: Test GCP Access
        run: |
          gcloud auth list
          gcloud projects list